### ISSUE TITLE
Wondering how this works exactly

### ISSUE THREAD

**Issue by TheSatanicAngeI** [shmkle/TemporalResampler#1]
So I have a ctl-472 and ever since I got my AOC monitor I could just not keep up with the game. Its been months that ive had it and it always felt like visually things were too fast for me to keep up. Disabling hardware GPU-Scheduling helped considerably with that and also turning off low latency mode on the monitor settings itself made visuals more smooth and slower. 

If I have a 240hz monitor with allegedly a 0.5ms delay, what frequency should I use ?  What does frequency do in that context ? Should I also use hawku filters with this or just default settings ?

This is all in context of osu! 

I'm just curious how this works and if this is viable long term to play with. Ive tested for awhile and im just shocked how accurate my movements are shown on screen but its still kinda weird. 

Also wanted to point out that hovering in and out of detection range in different tablet coordinates leads to "double teleportation" like the cursor glitches out and shows twice in different position. Dont know if its intended or a bug but it only happens with this plug in.

**Comment by TheSatanicAngeI** [comment]
I'm just wondering if im doing it right or not. 

![Capture](https://github.com/shmkle/TemporalResampler/assets/19210871/9a6d8a45-16b7-4e4a-86a2-916ca253e5c5)
![Capture2](https://github.com/shmkle/TemporalResampler/assets/19210871/fc812b17-7dab-4f9d-99ae-7bb8a6bb9399)

**Comment by shmkle** [comment]
The frame time shift value isn't in milliseconds, it's relative to your tablet's reporting speed, and higher means less latency. For example, the ctl-472 reports at 133hz, or 7.5ms per update. A value of 0.5 results in about 3.75ms latency, 0 gives around 7.5ms, and 1 means nearly 0ms. Adding some latency (using lower than 1) is better as it reduces the amount of fake predicted points, making your aim feel more predictable. I would recommend keeping this at the default 0.5 value.

Frequency should usually be left alone at 1000 because you'll notice any value that isn't 100, 250, 500, or 1000 will cause your CPU usage to rise significantly which will cause more stuttering, or uglier gaps in your cursor as you swipe it across your screen.

This filter is meant to be used alone and not with any other extrapolators or "upscaling" filters, basically anything with a frequency control. You can add smoothing by lowering the EMA Weight value from 1 and not ticking the Reverse Smoothing option, but that will introduce smoothing latency.

This filter is designed to work well when the pen is consistently in range.

Your setup is correct, don't use Hawku with this filter, and thank you for using my filter.

**Comment by TheSatanicAngeI** [comment]
Thank you for responding!

I'm looking into the info you provided and testing stuff

**Comment by TheSatanicAngeI** [comment]
@shmkle 
Ok so heres a video of me trying your filter. The only difference from the settings I showed is that I tried 0.9 EMA Weight. Do you have a spreadsheet or can you tell me the latency value introduced from 0.1 - 1 EMA Weight ? I'm not really the best at math 😂. 

Also let me know if you notice anything weird with the aiming specifically. The clicking is normal to be pretty bad but unrelated to the filter itself, I just have no idea how to use this uwu wooting keypad ive gotten a few months ago. Also yeah...the speed says -1ms thats correct...I dont know how to fix that, should I change usb port ? 

Also I want to point out that your filter is game changing for me. I mean it fixes a problem that I don't think anything else has managed to fix. Knowing I have a 240hz monitor (with 0.5ms input delay), everything else ive tried felt like my aiming in real time couldn't keep up with the screen. Also the screen was just too fast. I dont really know how to describe how it felt and the problem itself, but im convinced you know exactly what I mean since you made a piece of code to fix it 😂. Like I have tried many things... devocub filters (prediction and without), hawku filters, no filters even the damn wacom drivers itself...my aim always felt odd. 


> Adding some latency (using lower than 1) is better as it reduces the amount of fake predicted points, making your aim feel more predictable. I would recommend keeping this at the default 0.5 value.

Having tried this, I can confirm it seems to help a lot, at 1 EMA Weight it felt like I had BARELY any room to make movements cuz I was already on the next object. Reducing the EMA Weight is definitely accommodating. 

![image](https://github.com/shmkle/TemporalResampler/assets/19210871/9bdf065d-563c-435a-80cf-785f6dd02ab6)

https://link.issou.best/wHJOBl (this is the video but I assume you're familiar with o!rdr)


EDIT : I'd like to say shorter aiming has me confused for now and maybe its because I haven't played long enough with the filter. Bigger movements feels more natural and like how I expect them to work but yeah not shorter ones.

What about in-game settings ? Should absolute raw input be enabled or disabled ? Honestly im convinced it affects something about aiming and I used to play with it in the past.

**Comment by shmkle** [comment]
I released a new update that changes a few values, I'm hoping the new ones are easier to understand. I'm also hoping you can find the [wiki](https://github.com/shmkle/TemporalResampler/blob/main/README.md) more helpful too.
